project_id = "calegudnfdbeznyiebbh"

[functions.save-translation-fix]
verify_jwt = true

[functions.get-google-maps-token]
verify_jwt = false

[functions.import-google-maps-addresses]
verify_jwt = false

[functions.get-mapbox-token]
verify_jwt = false

[functions.analyze-photo-quality]
verify_jwt = false

[functions.analyze-coordinates]
verify_jwt = false

[functions.process-backup-request]
verify_jwt = true

[functions.external-api]
verify_jwt = false

[functions.webhook-delivery-processor]
verify_jwt = false

[functions.webhook-events]
verify_jwt = false

[functions.address-webhook-triggers]
verify_jwt = false