project_id = "calegudnfdbeznyiebbh"

[functions.get-google-maps-token]
verify_jwt = false

[functions.import-google-maps-addresses]
verify_jwt = false

[functions.get-mapbox-token]
verify_jwt = false

[functions.analyze-photo-quality]
verify_jwt = false

[functions.analyze-coordinates]
verify_jwt = false

[functions.process-backup-request]
verify_jwt = true

[functions.external-api]
verify_jwt = false