-- Create sample emergency units data
INSERT INTO public.emergency_units (unit_name, unit_code, unit_type, status, coverage_region, coverage_city, current_location, vehicle_id, radio_frequency) VALUES
('Unit Alpha-1', 'AL-01', 'patrol', 'available', 'Bioko Norte', 'Malabo', 'Downtown Malabo', 'VH-001', '154.250'),
('Unit Bravo-2', 'BR-02', 'rapid_response', 'on_duty', 'Bioko Norte', 'Malabo', 'Malabo Airport', 'VH-002', '154.275'),
('Unit Charlie-3', 'CH-03', 'patrol', 'available', 'Litoral', 'Bata', 'Bata City Center', 'VH-003', '154.300'),
('Unit Delta-4', 'DE-04', 'traffic', 'maintenance', 'Bioko Norte', 'Malabo', 'Police Station', 'VH-004', '154.325'),
('Unit Echo-5', 'EC-05', 'investigation', 'available', 'Litoral', 'Bata', 'Bata Port', 'VH-005', '154.350');

-- Create sample emergency incidents data
INSERT INTO public.emergency_incidents (
  incident_number, 
  emergency_type, 
  status, 
  priority_level, 
  location_latitude, 
  location_longitude, 
  location_address, 
  street, 
  city, 
  region, 
  country, 
  incident_message, 
  encrypted_message, 
  reporter_contact_info, 
  assigned_operator_id,
  reported_at,
  dispatched_at,
  responded_at
) VALUES
(
  'INC-2025-000001',
  'robbery',
  'resolved',
  1,
  3.7558,
  8.7784,
  'Malabo City Center',
  'Avenida de la Independencia',
  'Malabo',
  'Bioko Norte',
  'Equatorial Guinea',
  'Armed robbery reported at local business',
  'encrypted_incident_data_001',
  '+240666123456',
  (SELECT user_id FROM user_roles WHERE role = 'police_operator' LIMIT 1),
  now() - interval '2 hours',
  now() - interval '1 hour 45 minutes',
  now() - interval '1 hour 30 minutes'
),
(
  'INC-2025-000002',
  'traffic_accident',
  'on_scene',
  2,
  1.8548,
  9.7648,
  'Bata Main Road',
  'Carretera Nacional',
  'Bata',
  'Litoral',
  'Equatorial Guinea',
  'Vehicle collision with injuries',
  'encrypted_incident_data_002',
  '+240666234567',
  (SELECT user_id FROM user_roles WHERE role = 'police_dispatcher' LIMIT 1),
  now() - interval '30 minutes',
  now() - interval '25 minutes',
  now() - interval '15 minutes'
),
(
  'INC-2025-000003',
  'domestic_violence',
  'responding',
  1,
  3.7500,
  8.7800,
  'Residential Area Malabo',
  'Calle de la Paz',
  'Malabo',
  'Bioko Norte',
  'Equatorial Guinea',
  'Domestic violence incident reported',
  'encrypted_incident_data_003',
  '+240666345678',
  (SELECT user_id FROM user_roles WHERE role = 'police_operator' OFFSET 1 LIMIT 1),
  now() - interval '45 minutes',
  now() - interval '40 minutes',
  NULL
),
(
  'INC-2025-000004',
  'theft',
  'reported',
  3,
  1.8600,
  9.7600,
  'Bata Market Area',
  'Mercado Central',
  'Bata',
  'Litoral',
  'Equatorial Guinea',
  'Theft reported at local market',
  'encrypted_incident_data_004',
  '+240666456789',
  (SELECT user_id FROM user_roles WHERE role = 'police_dispatcher' OFFSET 1 LIMIT 1),
  now() - interval '10 minutes',
  NULL,
  NULL
),
(
  'INC-2025-000005',
  'public_disturbance',
  'dispatched',
  2,
  3.7520,
  8.7750,
  'Malabo University Area',
  'Campus Universitario',
  'Malabo',
  'Bioko Norte',
  'Equatorial Guinea',
  'Public disturbance near university',
  'encrypted_incident_data_005',
  '+240666567890',
  (SELECT user_id FROM user_roles WHERE role = 'police_supervisor' LIMIT 1),
  now() - interval '20 minutes',
  now() - interval '15 minutes',
  NULL
);

-- Create sample operator sessions
INSERT INTO public.emergency_operator_sessions (operator_id, status, session_start, active_incidents) VALUES
((SELECT user_id FROM user_roles WHERE role = 'police_operator' LIMIT 1), 'active', now() - interval '4 hours', ARRAY['INC-2025-000001', 'INC-2025-000003']),
((SELECT user_id FROM user_roles WHERE role = 'police_dispatcher' LIMIT 1), 'active', now() - interval '3 hours', ARRAY['INC-2025-000002', 'INC-2025-000004']),
((SELECT user_id FROM user_roles WHERE role = 'police_supervisor' LIMIT 1), 'active', now() - interval '2 hours', ARRAY['INC-2025-000005']);