// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://calegudnfdbeznyiebbh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNhbGVndWRuZmRiZXpueWllYmJoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwNDg5MTUsImV4cCI6MjA3MDYyNDkxNX0.tR4hLkiukz0F94lK1A9kmYLR8ibQf9CHhYrXgvEGRBM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});